function [fitresult, gof] = createFit(WH_hm0, Swan_Hsig)
%CREATEFIT(WH_HM0,SWAN_HSIG)
%  Create a fit.
%
%  Data for 'R=.9238' fit:
%      X Input : WH_hm0
%      Y Output: Swan_Hsig
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Feb-2022 01:35:56


%% Fit: 'R=.9238'.
[xData, yData] = prepareCurveData( WH_hm0, Swan_Hsig );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'R fit' );
h = plot( fitresult, xData, yData );
legend( h, 'Swan_Hsig vs. WH_hm0', 'R fit', 'Location', 'NorthWest', 'Interpreter', 'none' );
% Label axes
xlabel( 'WH_hm0', 'Interpreter', 'none' );
ylabel( 'Swan_Hsig', 'Interpreter', 'none' );
xlim([min(WH_hm0)-.1 max(WH_hm0)+.1])
ylim([min(Swan_Hsig)-.1 max(Swan_Hsig)+.1])
grid on


